### PR TITLE
VIH-9814 - Amend Master Release Pipeline

### PR DESCRIPTION
**Pull request by thomaswatsonv1**
### JIRA link (if applicable) ###

https://tools.hmcts.net/jira/browse/VIH-9814

### Change description ###

Remove acceptance tests and change staging to dev

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ X] No
```

### CODE REVIEW

**Review by v1ferrarij — APPROVED** [review]

**Review by oliver-scott — APPROVED** [review]

**Review by will-craig — APPROVED** [review]

**Review by thomaswatsonv1 — COMMENTED** [review]
/azp run hmcts.vh-video-api.sds.pr-release

**Pull request merged**
